### ISSUE TITLE
The command "guidellm benchmark --help" does not work with click version 8.2.1

### ISSUE THREAD

**Issue by pliops-daniels** [vllm-project/guidellm#228]
I installed guidellm (from source) on a new python venv (python 3.10).
When I try to run `guidellm benchmark --help` I get this error:
```
  File "/.../python3.10/site-packages/click/core.py", line 2212, in make_metavar
    metavar = self.type.get_metavar(param=self, ctx=ctx)
TypeError: Union.get_metavar() got an unexpected keyword argument 'ctx'
```

This error is related to the `click` package, after a quick search I found that this issue is related to click version 8.
So I downgraded click to version 7:
```bash
pip install click==7.1.2
...
      Successfully uninstalled click-8.2.1
Successfully installed click-7.1.2
```

And the `--help` worked with that version.

**Comment by sjmonson** [comment]
@pliops-daniels this issue has been fixed on `main`. Please downgrade to click `8.0.0` not `7.1.2`.
