### PR TITLE
fix: validate only the required columns in trace files

### PR DESCRIPTION
**Pull request by QHarshil**
## Summary

Trace validation casts each conversation to the required feature set and scans every column for nulls. `Dataset.cast` requires the column sets to match, so a trace carrying any column beyond the required ones is rejected before the benchmark starts. A null in a column the deserializer never reads fails the same way.

Real traces carry that metadata. The WEKA specification defines `model`, `type`, `input_types`, `output_types` and `stop` on every request record, plus optional `api_time`, `ttft` and `think_time`. A trace that follows it cannot be loaded:

```
DataNotSupportedError: The columns in features (['t', 'in', 'out', 'hash_ids'])
must be identical as the columns in the dataset:
['t', 'type', 'model', 'in', 'out', 'hash_ids', 'input_types', 'output_types', 'stop']
```

The reference trace from the specification fails on this, and so does `semianalysisai/cc-traces-weka-no-subagents-051226`, which `docs/guides/trace_replay.md` links to as an example. That dataset carries five of those fields, and 471 of its 949 conversations omit `ttft` or `think_time` on at least one record, which trips the null scan.

The guide already describes the intended behavior: `trace_synthetic` looks only at the timestamp, prompt token count and output token count columns, "ignoring all other features contained in a dataset". This change restores that for all three formats. Traces containing only the required columns are unaffected.

Before #1012 the validation loop ran per required column, and its docstring described the contract as "A required column contains a NoneType" and "A required column failed during cast to feature type". #1012 widened both checks to the whole dataset.

This does not implement nested WEKA subagent replay. With this fixed, the canonical subagent trace gets past top-level schema validation and then fails on the nested records, which is tracked by #992.

## Details

- [x] `_raise_if_incorrect_types` selects the required columns before casting, so unrelated columns are neither constrained nor copied
- [x] a shape mismatch in a required column raises `TypeError` rather than `ValueError` and previously escaped the deserializer uncaught, so both are now converted to `DataNotSupportedError`
- [x] `_raise_if_nonetype_found` takes the required features and checks only those columns
- [x] tests that extra columns and nulls outside the required columns are accepted, and that a null, a bad scalar type or a bad shape in a required column is still rejected

## Test Plan

- `tox -e lint-check` and `tox -e type-check`: clean
- `tox -e tests -- tests/unit/data/deserializers/`: 200 passed, 1 skipped
- `tox -e test-unit`: 2936 passed, excluding 14 `tests/unit/utils/test_audio.py` failures from a missing local FFmpeg library that fail identically on `main`
- `tox -e test-integration`: 27 passed
- `tox -e test-e2e`: 13 passed, with the same local FFmpeg error on `main`
- checked all three registered formats: `trace_synthetic`, `mooncake` and `weka` traces carrying extra columns are rejected on `main` and load on this branch
- loaded the reference `sample_trace.json` from the specification and the first 30 conversations of `cc-traces-weka-no-subagents-051226`, both of which fail on `main`

## Related Issues

- Prerequisite for #992

---

- [x] "I certify that all code in this PR is my own, except as noted below."

## Use of AI

- [x] Includes code generated or substantially modified by an AI agent
- [x] Includes tests generated or substantially modified by an AI agent

---

# git log

commit 08e5a77801fc1dc58b4a8ceb61c4ff5c01e9ffb9
Author: QHarshil <harshil_c@hotmail.com>
Date:   Mon Aug 31 13:36:36 2026 -0700

    fix: validate only the required columns in trace files
    
    Trace validation cast each conversation to the required feature set and
    scanned every column for nulls. Dataset.cast requires the column sets to
    match, so a trace carrying any extra column was rejected, and a null in a
    column the deserializer never reads failed validation the same way.
    
    The WEKA specification defines model, type, input_types, output_types and
    stop on every request record, alongside optional api_time, ttft and
    think_time, so no trace that follows it can be loaded. The reference trace
    from the specification fails on this, as does the
    semianalysisai/cc-traces-weka-no-subagents-051226 dataset linked from
    docs/guides/trace_replay.md, which carries five of those fields. That guide
    already describes trace_synthetic as ignoring all other features contained
    in a dataset.
    
    Select the required columns before casting, and check only those for nulls,
    so unrelated columns are ignored. A shape mismatch in a required column
    surfaces as TypeError rather than ValueError, and previously escaped the
    deserializer uncaught, so convert both to DataNotSupportedError.
    
    Signed-off-by: QHarshil <harshil_c@hotmail.com>
    Generated-by: Claude Code claude-opus-5

---------

Generated-by: Claude Code claude-opus-5
Signed-off-by: QHarshil <harshil_c@hotmail.com>

### CODE REVIEW

**Comment by QHarshil** [comment]
Some overlap with #1071, which opened just before this one.

I ran the same validation cases against its branch. It fixes the WEKA spec-metadata case as part of the subagent work, by projecting nested API rows down to the required columns before validation. The generic problem is still there: `trace_synthetic` and `mooncake` with extra columns are rejected, and a shape mismatch in a required column still escapes as `TypeError`.

The two conflict in `trace_common.py`, since #1071 moves validation behind a new `TraceFormatBase.validate_conversation()` hook while this changes the shared helpers. If #1071 lands first I am happy to rebase and apply the required-column-only behavior to the default `validate_conversation()`, leaving the WEKA override as it is.

**Comment by jaredoconnell** [comment]
This looks good. I can approve it once CI is passing. It's currently failing.

**Comment by QHarshil** [comment]
@jaredoconnell 
> This looks good. I can approve it once CI is passing. It's currently failing.

Thank you. The two failures don’t seem related to this: the quality job failed fetching the uv manifest before tox ran, and integration failed on the synthetic video timeout.

 I don’t appear to have permission to rerun the upstream Actions run. Could you rerun the failed jobs when you get a chance?

**Review by jaredoconnell — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]
