### ISSUE TITLE
评测自己的服务发生报错AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

### ISSUE THREAD

**Issue by Ladazhx** [vllm-project/guidellm#278]
**Describe the bug**
当我使用本项目评测我本地启动的模型服务时，跑一会就会发生报错

<img width="1250" height="570" alt="Image" src="https://github.com/user-attachments/assets/d8c83cf8-e95b-4d27-879a-9ecd597c2b2f" />

**start command**
python run.py benchmark --target "http://10.16.2.3:11092" --model Qwen2_5-VL-7B-Instruct --processor /Users/huizhang/Develop/ai/model/Qwen2.5-VL-7B-Instruct --rate-type sweep --max-seconds 60 --data "prompt_tokens=512,output_tokens=10"

**Environment**
Include all relevant environment information:
1. OS: macOS 12.7.3
2. Python version : 3.10.15

帮忙确定一下是什么环节的问题

**Comment by markurtz** [comment]
@Ladazhx  please double check if this is now working with the 0.3.0 that went out. If not, 0.4.0 will enable full control over how the processes are forked/created
